src/Edspim/Bundle/AppBundle/Entity/Doctorant.php
<?php

namespace Edspim\Bundle\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Doctorant
 *
 * @ORM\Table("Doctorant")
 * @ORM\Entity(repositoryClass="Edspim\Bundle\AppBundle\Entity\Repository\DoctorantRepository")
 */
class Doctorant {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=50)
     * 
     * @Assert\Length(
     *      min = "2",
     *      max = "50"
     * )
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="prenom", type="string", length=50)
     * 
     * @Assert\Length(
     *      min = "2",
     *      max = "50"
     * )
     */
    private $prenom;

    /**
     * @var email
     *
     * @ORM\Column(name="email", type="string", length=75)
     * 
     * @Assert\Email()
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="labDpt", type="string", length=50, nullable=true)
     * 
     * @Assert\Length(
     *      min = "2",
     *      max = "50"
     * )
     */
    private $labDpt;

    /**
     * @var string
     *
     * @ORM\Column(name="statutDoctorant", type="string", length=50)
     * 
     * @Assert\Choice(choices = 
     *      {   "doctorant.statutDoctorant.actif", 
     *          "doctorant.statutDoctorant.fini", 
     *          "doctorant.statutDoctorant.clos", 
     *      }, 
     *      message = "Choisissez un statut valide.")
     */
    private $statutDoctorant;

    /**
     * @var integer
     *
     * @ORM\Column(name="anneeDoctorant", type="integer")
     * 
     * @Assert\Range(
     *      min = 1,
     *      max = 3,
     *      minMessage = "Année 1 minimum",
     *      maxMessage = "Année 3 maximum"
     * )
     */
    private $anneeDoctorant;

    /**
     * @ORM\OneToMany(targetEntity="Edspim\Bundle\AppBundle\Entity\CoursDoctorant", mappedBy="doctorant")
     */
    protected $coursDoctorant;

    /**
     * @ORM\OneToMany(targetEntity="Edspim\Bundle\AppBundle\Entity\CoursPif", mappedBy="doctorant")
     */
    private $coursPif;
    
    /**
     * @ORM\OneToMany(targetEntity="Edspim\Bundle\AppBundle\Entity\SeanceDoctorant", mappedBy="doctorant")
     */
    private $seanceDoctorant;

    /**
     * Fonction standard toString
     * 
     * @return string nom et prénom
     */
    public function __toString() {
        return $this->prenom . " " . $this->nom;
    }

    public function getAnneeToString() {
        $annee = '';
        switch ($this->anneeDoctorant) {
            case 1 :
                $annee = 'doctorant.1annee';
                break;
            case 2 :
                $annee = 'doctorant.2annee';
                break;
            case 3:
                $annee = 'doctorant.3annee';
                break;
        }
        return $annee;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     * @return Doctorant
     */
    public function setNom($nom) {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string 
     */
    public function getNom() {
        return $this->nom;
    }

    /**
     * Set prenom
     *
     * @param string $prenom
     * @return Doctorant
     */
    public function setPrenom($prenom) {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get prenom
     *
     * @return string 
     */
    public function getPrenom() {
        return $this->prenom;
    }

    /**
     * Set labDpt
     *
     * @param string $labDpt
     * @return Doctorant
     */
    public function setLabDpt($labDpt) {
        $this->labDpt = $labDpt;

        return $this;
    }

    /**
     * Get labDpt
     *
     * @return string 
     */
    public function getLabDpt() {
        return $this->labDpt;
    }

    /**
     * Set statutDoctorant
     *
     * @param string $statutDoctorant
     * @return Doctorant
     */
    public function setStatutDoctorant($statutDoctorant) {
        $this->statutDoctorant = $statutDoctorant;

        return $this;
    }

    /**
     * Get statutDoctorant
     *
     * @return string 
     */
    public function getStatutDoctorant() {
        return $this->statutDoctorant;
    }

    /**
     * Set anneeDoctorant
     *
     * @param integer $anneeDoctorant
     * @return Doctorant
     */
    public function setAnneeDoctorant($anneeDoctorant) {
        $this->anneeDoctorant = $anneeDoctorant;

        return $this;
    }

    /**
     * Get anneeDoctorant
     *
     * @return integer 
     */
    public function getAnneeDoctorant() {
        return $this->anneeDoctorant;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Doctorant
     */
    public function setEmail($email) {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail() {
        return $this->email;
    }

    /**
     * Constructor
     */
    public function __construct() {
        $this->coursDoctorant = new \Doctrine\Common\Collections\ArrayCollection();
        $this->anneeDoctorant = 1;
        $this->statutDoctorant = "doctorant.statutDoctorant.actif";
    }

    /**
     * Add coursDoctorant
     *
     * @param \Edspim\Bundle\AppBundle\Entity\CoursDoctorant $coursDoctorant
     * @return Doctorant
     */
    public function addCoursDoctorant(\Edspim\Bundle\AppBundle\Entity\CoursDoctorant $coursDoctorant) {
        $this->coursDoctorant[] = $coursDoctorant;

        return $this;
    }

    /**
     * Remove coursDoctorant
     *
     * @param \Edspim\Bundle\AppBundle\Entity\CoursDoctorant $coursDoctorant
     */
    public function removeCoursDoctorant(\Edspim\Bundle\AppBundle\Entity\CoursDoctorant $coursDoctorant) {
        $this->coursDoctorant->removeElement($coursDoctorant);
    }

    /**
     * Get coursDoctorant
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getCoursDoctorant() {
        return $this->coursDoctorant;
    }
    
    public function getCoursDoctorantActif() {
        $actif = new \Doctrine\Common\Collections\ArrayCollection();
        foreach($this->coursDoctorant as $cd) {
            if(in_array($cd->getStatut(), array("coursdoc.statut.inscription", "coursdoc.statut.actif"))) {
                $actif->add($cd);
            }
        }
        return $actif;
    }


    /**
     * Add coursPif
     *
     * @param \Edspim\Bundle\AppBundle\Entity\CoursPif $coursPif
     * @return Doctorant
     */
    public function addCoursPif(\Edspim\Bundle\AppBundle\Entity\CoursPif $coursPif)
    {
        $this->coursPif[] = $coursPif;

        return $this;
    }

    /**
     * Remove coursPif
     *
     * @param \Edspim\Bundle\AppBundle\Entity\CoursPif $coursPif
     */
    public function removeCoursPif(\Edspim\Bundle\AppBundle\Entity\CoursPif $coursPif)
    {
        $this->coursPif->removeElement($coursPif);
    }

    /**
     * Get coursPif
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getCoursPif()
    {
        return $this->coursPif;
    }

   

    /**
     * Add seanceDoctorant
     *
     * @param \Edspim\Bundle\AppBundle\Entity\SeanceDoctorant $seanceDoctorant
     * @return Doctorant
     */
    public function addSeanceDoctorant(\Edspim\Bundle\AppBundle\Entity\SeanceDoctorant $seanceDoctorant)
    {
        $this->seanceDoctorant[] = $seanceDoctorant;

        return $this;
    }

    /**
     * Remove seanceDoctorant
     *
     * @param \Edspim\Bundle\AppBundle\Entity\SeanceDoctorant $seanceDoctorant
     */
    public function removeSeanceDoctorant(\Edspim\Bundle\AppBundle\Entity\SeanceDoctorant $seanceDoctorant)
    {
        $this->seanceDoctorant->removeElement($seanceDoctorant);
    }

    /**
     * Get seanceDoctorant
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getSeanceDoctorant()
    {
        return $this->seanceDoctorant;
    }
    
}

src/Edspim/Bundle/AppBundle/Entity/Enseignant.php
<?php

namespace Edspim\Bundle\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Enseignant
 *
 * @ORM\Table("Enseignant")
 * @ORM\Entity(repositoryClass="Edspim\Bundle\AppBundle\Entity\Repository\EnseignantRepository")
 */
class Enseignant {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=50)
     * 
     * @Assert\Length(
     *      min = "2",
     *      max = "50"
     * )
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="prenom", type="string", length=50)
     * 
     * @Assert\Length(
     *      min = "2",
     *      max = "50"
     * )
     */
    private $prenom;

    /**
     * @var email
     *
     * @ORM\Column(name="email", type="string", length=75)
     * 
     * @Assert\Email()
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="labDpt", type="string", length=50, nullable=true)
     * 
     * @Assert\Length(
     *      min = "2",
     *      max = "50"
     * )
     */
    private $labDpt;

    /**
     * @var string
     *
     * @ORM\Column(name="institut", type="string", length=50, nullable=true)
     * 
     * @Assert\Length(
     *      min = "2",
     *      max = "50"
     * )
     */
    private $institut;

    /**
     * @var string
     *
     * @ORM\Column(name="fonction", type="string", length=50, nullable=true)
     * 
     * @Assert\Length(
     *      min = "2",
     *      max = "50"
     * )
     */
    private $fonction;

    /**
     * @ORM\OneToMany(targetEntity="Edspim\Bundle\AppBundle\Entity\EnseignantCours", mappedBy="enseignant", cascade={"persist"})
     */
    private $enseignantCours;

    /**
     * Fonction standard toString
     * 
     * @return string nom et prénom
     */
    public function __toString() {
        return $this->prenom . " " . $this->nom;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     * @return Enseignant
     */
    public function setNom($nom) {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string 
     */
    public function getNom() {
        return $this->nom;
    }

    /**
     * Set prenom
     *
     * @param string $prenom
     * @return Enseignant
     */
    public function setPrenom($prenom) {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get prenom
     *
     * @return string 
     */
    public function getPrenom() {
        return $this->prenom;
    }

    /**
     * Set labDpt
     *
     * @param string $labDpt
     * @return Enseignant
     */
    public function setLabDpt($labDpt) {
        $this->labDpt = $labDpt;

        return $this;
    }

    /**
     * Get labDpt
     *
     * @return string 
     */
    public function getLabDpt() {
        return $this->labDpt;
    }

    /**
     * Set institut
     *
     * @param string $institut
     * @return Enseignant
     */
    public function setInstitut($institut) {
        $this->institut = $institut;

        return $this;
    }

    /**
     * Get institut
     *
     * @return string 
     */
    public function getInstitut() {
        return $this->institut;
    }

    /**
     * Set fonction
     *
     * @param string $fonction
     * @return Enseignant
     */
    public function setFonction($fonction) {
        $this->fonction = $fonction;

        return $this;
    }

    /**
     * Get fonction
     *
     * @return string 
     */
    public function getFonction() {
        return $this->fonction;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Enseignant
     */
    public function setEmail($email) {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail() {
        return $this->email;
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->enseignantCours = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add enseignantCours
     *
     * @param \Edspim\Bundle\AppBundle\Entity\EnseignantCours $enseignantCours
     * @return Enseignant
     */
    public function addEnseignantCour(\Edspim\Bundle\AppBundle\Entity\EnseignantCours $enseignantCours)
    {
        $this->enseignantCours[] = $enseignantCours;

        return $this;
    }

    /**
     * Remove enseignantCours
     *
     * @param \Edspim\Bundle\AppBundle\Entity\EnseignantCours $enseignantCours
     */
    public function removeEnseignantCour(\Edspim\Bundle\AppBundle\Entity\EnseignantCours $enseignantCours)
    {
        $this->enseignantCours->removeElement($enseignantCours);
    }

    /**
     * Get enseignantCours
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getEnseignantCours()
    {
        return $this->enseignantCours;
    }
    
    public function getCoursActif() {
        $actif = new \Doctrine\Common\Collections\ArrayCollection();
        foreach($this->enseignantCours as $ensCours) {
            if(in_array($ensCours->getCours()->getStatutCours(), array(
                "cours.statutCours.archive", 
                "cours.statutCours.inscription", 
                "cours.statutCours.ouvert"))) {
                $actif->add($ensCours);
            }
        }
        return $actif;
    }
}

src/Edspim/Bundle/AppBundle/Resources/views/Default/coursListe.html.twig
{% extends 'EdspimAppBundle::layout.html.twig' %}
{% set nomPage = 'page.coursListe.nom' | trans %}
{% block title %}{{ nomPage }} {% endblock %}
{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{{ path('edspim_portail')}}">{{ 'page.vue.nom' | trans }}</a></li>
        <li class="active">{{ nomPage }}</li>
    </ol>
{% endblock %}
{% block content %}
    <h2>{{ nomPage }}</h2>
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                {{ form_start(form, {'attr': {'class': 'navbar-form navbar-left'} }) }}
                <div class="form-group">
                    {{ form_widget(form.rechercheParNom, {'required' : false ,'attr': {'class': 'form-control', 'placeholder' : 'Recherche par nom'} } ) }}
                </div>
                <div class="form-group">
                    {{ form_widget(form.rechercheParVille, {'required' : false ,'attr': {'class': 'form-control', 'placeholder' : 'Recherche par ville'} } ) }}
                </div>
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                    {{ form_end(form) }}
            </div>
        </div>
    </nav>
    {% if coursListe | length != 0 %}
        <table class="table table-condensed table-hover">
            <tr>
                <th>{{ 'cours.titre' | trans }}</th>
                <th>{{ 'cours.lieu' | trans }}</th>
                <th>{{ 'cours.typeCours.nom' | trans }}</th>
                <th>{{ 'cours.statutCours.nom' | trans }}</th>
                <th></th>
            </tr>
            {% for cour in coursListe %}
                <tr>
                    <td>{{ cour }}</td>
                    <td>{{ cour.lieu }}</td>
                    <td>{{ cour.typeCours | trans }}</td>
                    <td>{{ cour.statutCours | trans }}</td>
                    <td><a href="{{ path('edspim_cours', {'cours' : cour.id })}}" class="btn btn-sm btn-success">Voir le cours</a></td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <br/>
        <div class="alert alert-warning">
            {{ 'page.coursListe.info1' | trans }}
        </div>
    {% endif %}
{% endblock %}

src/Edspim/Bundle/AppBundle/Resources/views/Default/cours_gestion.html.twig
<br/>
{% if cours.statutCours == 'cours.statutCours.archive' %}
    <table class="table">
        <tr>
            <td><a href="{{ path('edspim_ed_cours_changer_statut', {'cours' : cours.id, 'statut' : 'inscription'}) }}" class="btn btn-default">Ouvrir ce cours aux inscriptions</a></td>
            <td></td>
        </tr>
        <tr>
            <td><a href="{{ path('edspim_ed_cours_modifier', {'cours' : cours.id}) }}" class="btn btn-default">Modifier les informations du cours</a></td>
            <td></td>
        </tr>
    </table>
{% elseif cours.statutCours == 'cours.statutCours.inscription' %}
    <table class="table">
        <tr>
            <td><a href="{{ path('edspim_ed_cours_changer_statut', {'cours' : cours.id, 'statut' : 'ouverture'}) }}" class="btn btn-default">Finaliser les inscriptions et ouvrir le cours</a></td>
            <td></td>
        </tr>
        <tr>
            <td><a href="{{ path('edspim_ed_cours_changer_statut', {'cours' : cours.id, 'statut' : 'annulation'}) }}" class="btn btn-default">Annuler les inscriptions et remettre le cours en archive</a></td>
            <td></td>
        </tr>
    </table>
{% elseif cours.statutCours == 'cours.statutCours.ouvert' %}
     <table class="table">
        <tr>
            <td><a href="{{ path('edspim_ed_cours_changer_statut', {'cours' : cours.id, 'statut' : 'archivage'}) }}" class="btn btn-default">Clore le cours</a></td>
            <td></td>
        </tr>
    </table>
{% endif %}

src/Edspim/Bundle/AppBundle/Resources/views/Default/doctorant.html.twig
{% extends 'EdspimAppBundle::layout.html.twig' %}
{% set nomPage = 'page.doctorant.nom' | trans ~ ' ' ~ doctorant %}
{% block title %}{{ nomPage }}{% endblock %}
{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{{ path('edspim_portail')}}">{{ 'page.vue.nom' | trans }}</a></li>
        <li><a href="{{ path('edspim_doctorant_liste')}}">{{ 'page.doctorantListe.nom' | trans }}</a></li>
        <li class="active">{{ nomPage }}</li>
    </ol>
{% endblock %}
{% block content %}
    <h2>{{ nomPage }}</h2>
    <ul class="nav nav-tabs">
        <li class="active"><a href="#info" data-toggle="tab">{{ 'page.doctorant.info' | trans }}</a></li>
        <li><a href="#coursActuels" data-toggle="tab">{{ 'page.doctorant.coursActuels' | trans }}</a></li>
            {% if is_granted('ROLE_ED') %}
            <li><a href="#gestioNCours" data-toggle="tab">{{ 'page.coursGestion.nom' | trans }}</a></li>
            {% endif %}
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="info">
            <br/>
            <div class="col-md-6">
                <table class="table">
                    <tr>
                        <th>Statut</th>
                        <td>{{ doctorant.statutDoctorant | trans }}</td>
                    </tr>
                    <tr>
                        <th>{{ 'doctorant.prenom' | trans }}</th>
                        <td>{{ doctorant.prenom }}</td>
                    </tr>
                    <tr>
                        <th>{{ 'doctorant.nom' | trans }}</th>
                        <td>{{ doctorant.nom }}</td>
                    </tr>
                    <tr>
                        <th>{{ 'utilisateur.email' | trans }}</th>
                        <td>{{ doctorant.email }}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-6">
                <table class="table">
                    <tr>
                        <th>{{ 'doctorant.labDpt' | trans }}</th>
                        <td>{{ doctorant.labDpt }}</td>
                    </tr>
                    <tr>
                        <th>{{ 'doctorant.annee' | trans }}</th>
                        <td>{{ doctorant.anneeToString | trans }}</td>
                    </tr>
                    {% if is_granted('ROLE_ED') %}
                        <tr>
                            <th>PIF</th>
                            <td><a href="{{ path('edspim_ed_pif', {'doctorant' : doctorant.id }) }}">Voir le PIF</a></td>
                        </tr>
                    {% endif %}
                </table>
            </div>
        </div>
        <div class="tab-pane" id="coursActuels">
            <br/>
            {% if doctorant.coursDoctorantActif | length != 0 %}
                <table class="table">
                    <tr>
                        <th>{{ 'cours.titre' | trans }}</th>
                        <th>{{ 'cours.lieu' | trans }}</th>
                        <th>{{ 'cours.typeCours.nom' | trans }}</th>
                        <th>{{ 'cours.statutCours.nom' | trans }}</th>
                        <th></th>
                    </tr>
                    {% for c in doctorant.coursDoctorantActif %}
                        <tr>
                            <td>{{ c.cours.titre }}</td>
                            <td>{{ c.cours.lieu }}</td>
                            <td>{{ c.cours.typeCours | trans }}</td>
                            <td>{{ c.cours.statutCours | trans }}</td>
                            <td><a href="{{ path('edspim_cours', {'cours' : c.cours.id })}}" class="btn btn-sm btn-success">{{ 'page.coursListe.voirCours' | trans }}</a></td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <div class="alert alert-warning">
                    {{ 'page.doctorant.coursActifs' | trans }}
                </div>
            {% endif %}




        </div>
        {% if is_granted('ROLE_ED') %}
            <div class="tab-pane" id="gestioNCours">
                <br/>
                <a href="{{ path('edspim_ed_pif', {'doctorant' : doctorant.id }) }}" class="btn btn-sm btn-default">Voir le PIF</a>
                {% if doctorant.statutDoctorant != "doctorant.statutDoctorant.clos" %}
                    <a href="{{ path('edspim_ed_ajouter_pif', {'doctorant' : doctorant.id })}}" class="btn btn-sm btn-success">Ajouter un cours dans le PIF</a>
                    <a href="{{ path('edspim_ed_desactiver_doc', {'doctorant' : doctorant.id }) }}" class="btn btn-sm btn-danger">Désactiver le compte</a>
                {% endif %}
                <br/><br/>
                <table class="table">
                    <tr>
                        <th>{{ 'cours.titre' | trans }}</th>
                        <th>{{ 'doctorant.annee' | trans }}</th>
                        <th>{{ 'cours.typeCours.nom' | trans }}</th>
                        <th>{{ 'doctorant.heureValidees' | trans }}</th>
                        <th></th>
                    </tr>
                    {% for coursPif in doctorant.coursPif %}
                        <tr>
                            <td>{{ coursPif.nomCoursPif }}</td>
                            <td>{{ coursPif.anneePif }}</td>
                            <td>{{ coursPif.typeCours | trans }}</td>
                            <td>{{ coursPif.heureValidees }}</td>
                            <td><a href="{{ path('edspim_ed_modifier_pif', {'coursPif' : coursPif.id })}}" class="btn btn-sm btn-default">Modifier</a> <a href="{{ path('edspim_ed_supprimer_pif', {'pif' : coursPif.id })}}" class="btn btn-sm btn-default">Supprimer</a></td>
                        </tr>
                    {% endfor%}
                </table>
            </div>
        {% endif %}
    </div>
{% endblock %}

src/Edspim/Bundle/AppBundle/Resources/views/Default/mail_suppression.html.twig
Bonjour.

Votre compte {{ username }} a été supprimé du portail ED SPIM.

Merci.

src/Edspim/Bundle/AppBundle/Resources/views/Default/portail_enseignant.html.twig
{% extends 'EdspimAppBundle::layout.html.twig' %}
{% set nomPage = 'page.vue.nom' | trans %}
{% block title %}{{ nomPage }} {% endblock %}
{% block breadcrumb %}
    <ol class="breadcrumb">
        <li class="active">{{ nomPage }}</li>
    </ol>
{% endblock %}
{% set enseignant = app.user.enseignant %}
{% block content %}
    <h2>{{ enseignant }}</h2>
    <ul class="nav nav-tabs">
        <li class="active"><a href="#info" data-toggle="tab">{{ 'page.enseignant.info' | trans }}</a></li>
        <li><a href="#coursActuels" data-toggle="tab">{{ 'page.enseignant.coursActuels' | trans }} <span class="badge">{{ enseignant.coursActif | length }}</span></a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="info">
            <br/>
            <div class="col-md-6">
                <table class="table">
                    <tr>
                        <th>{{ 'enseignant.prenom' | trans }}</th>
                        <td>{{ enseignant.prenom }}</td>
                    </tr>
                    <tr>
                        <th>{{ 'enseignant.nom' | trans }}</th>
                        <td>{{ enseignant.nom }}</td>
                    </tr>
                    <tr>
                        <th>{{ 'utilisateur.email' | trans }}</th>
                        <td>{{ enseignant.email }}</td>
                    </tr>
                    <tr>
                        <th>{{ 'enseignant.fonction' | trans }}</th>
                        <td>{{ enseignant.fonction }}</td>
                    </tr>
                    <tr>
                        <th>{{ 'enseignant.labDpt' | trans }}</th>
                        <td>{{ enseignant.labDpt | trans }}</td>
                    </tr>
                    <tr>
                        <th>{{ 'enseignant.institut' | trans }}</th>
                        <td>{{ enseignant.institut | trans }}</td>
                    </tr>
                    <tr>
                        <th></th>
                        <td><a href="#" class="btn btn-default btn-sm">{{ 'page.vue.modifierInfo' | trans }}</a></td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="tab-pane" id="coursActuels">
            <br/>
            {% if enseignant.coursActif | length != 0 %}
            <table class="table">
                <tr>
                    <th>{{ 'cours.titre' | trans }}</th>
                    <th>{{ 'cours.lieu' | trans }}</th>
                    <th>{{ 'cours.typeCours.nom' | trans }}</th>
                    <th>{{ 'cours.statutCours.nom' | trans }}</th>
                    <th></th>
                </tr>
                {% for c in enseignant.coursActif %}
                    <tr>
                        <td>{{ c.cours.titre }}</td>
                        <td>{{ c.cours.lieu }}</td>
                        <td>{{ c.cours.typeCours | trans }}</td>
                        <td>{{ c.cours.statutCours | trans }}</td>
                        <td><a href="{{ path('edspim_cours', {'cours' : c.cours.id })}}" class="btn btn-sm btn-success">{{ 'page.coursListe.voirCours' | trans }}</a></td>
                    </tr>
                {% endfor %}
            </table>
            {% else %}
                <div class="alert alert-warning">
                    {{ 'page.vue.info1' | trans }}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

src/Edspim/Bundle/AppBundle/Resources/views/Default/seanceDetail.html.twig
<table class="table table-hover">
    <tr>
         <th>{{ 'seance.dateSeance' | trans }}</th>
        <td>{{ seance.dateSeance | date('D d/m/y') }} {{ seance.heureSeance | date('H:i')}}</td>
    </tr>
    <tr>
        <th>{{ 'seance.typeSeance.nom' | trans }}</th>
        <td>{{ seance.nbHeures }}h de {{ seance.typeSeance | trans }}</td>
    </tr>
    <tr>
        <th>{{ 'seance.salle' | trans }}</th>
        <td>{{ seance.salle }}</td>
    </tr>
    <tr>
        <th>{{ 'seance.batiment' | trans }}</th>
        <td>{{ seance.batiment }}</td>
    </tr>
    <tr>
        <th>{{ 'seance.adresse' | trans }}</th>
        <td>{{ seance.adresse }}</td>
    </tr>
    <tr>
        <th>{{ 'seance.lieu' | trans }}</th>
        <td>{{ seance.lieu }}</td>
    </tr>
</table>